---
abstract: "Perl interface to Janrain's RPX service"
author:
  - 'Scott McWhirter <konobi@cpan.org>'
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  Data::Dump: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::Exception: 0
  Test::More: 0.88
  mocked: 0
  unmocked: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120921'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-API-RPX
provides:
  Net::API::RPX:
    file: lib/Net/API/RPX.pm
    version: 0.03
  Net::API::RPX::Exception:
    file: lib/Net/API/RPX/Exception.pm
    version: 0.03
  Net::API::RPX::Exception::Network:
    file: lib/Net/API/RPX/Exception/Network.pm
    version: 0.03
  Net::API::RPX::Exception::Service:
    file: lib/Net/API/RPX/Exception/Service.pm
    version: 0.03
  Net::API::RPX::Exception::Usage:
    file: lib/Net/API/RPX/Exception/Usage.pm
    version: 0.03
requires:
  JSON::Any: 0
  LWP::UserAgent: 0
  Moose: 0
  Throwable::Error: 0
  Throwable::X: 0
  URI: 0
  namespace::autoclean: 0
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/kentfredric/net-api-rpx
  repository: https://github.com/kentfredric/net-api-rpx.git
version: 0.03
x_BuiltWith:
  modules:
    Data::Dump: 1.21
    File::Find: 1.20
    File::Temp: 0.22
    JSON::Any: 1.29
    LWP::UserAgent: 6.04
    Module::Build: 0.4
    Moose: 2.0602
    Test::Exception: 0.31
    Test::More: 0.98
    Throwable::Error: 0.102080
    Throwable::X: 0.006
    URI: 1.60
    mocked: 0.09
    namespace::autoclean: 0.13
    strict: 1.07
    unmocked: 0.01
    warnings: 1.13
  perl:
    original: v5.16.0
    qv: 1
    version:
      - 5
      - 16
      - 0
  perl-config:
    gccversion: 4.5.3
    myarchname: x86_64-linux
    osname: linux
  platform: linux
  uname: 'Linux 3.4.0-gentoo x86_64 GenuineIntel GNU/Linux'
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: Git::NextVersion
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: GithubMeta
      version: 0.28
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: MetaProvides::Package
      version: 1.14000001
    -
      class: Dist::Zilla::Plugin::MetaData::BuiltWith
      config:
        Dist::Zilla::Plugin::MetaData::BuiltWith:
          _stash_key: x_BuiltWith
          show_config: 1
          show_uname: 1
          uname:
            uname_args:
              - '-s'
              - '-o'
              - '-r'
              - '-m'
              - '-i'
            uname_call: uname
      name: MetaData::BuiltWith
      version: 0.03000000
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      name: Git::GatherDir
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::License
      name: License
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: MetaYAML
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::Manifest
      name: Manifest
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: MetaTests
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: PodCoverageTests
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: PodSyntaxTests
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: ReportVersions::Tiny
      version: 1.03
    -
      class: Dist::Zilla::Plugin::Test::Kwalitee
      name: Test::Kwalitee
      version: 2.03
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: EOLTests
      version: 0.02
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: Test::MinimumVersion
      version: 2.0.1
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: Test::Compile
      version: 1.112820
    -
      class: Dist::Zilla::Plugin::Test::Perl::Critic
      name: Test::Perl::Critic
      version: 2.112410
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: PruneCruft
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: ManifestSkip
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: PkgVersion
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: PodWeaver
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: NextRelease
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::Authority
      name: Authority
      version: 1.006
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: ModuleBuild
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: ReadmeFromPod
      version: 0.16
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: Test::CPAN::Changes
      version: 0.005
    -
      class: Dist::Zilla::Plugin::CheckExtraTests
      name: CheckExtraTests
      version: 0.006
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: TestRelease
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: ConfirmRelease
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: Git::Check
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: tag_master
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: Git::Commit
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: Git::CommitBuild
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: tag_release
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: UploadToCPAN
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::Twitter
      name: Twitter
      version: 0.016
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300016
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300016
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300016
x_authority: cpan:KONOBI
