---
abstract: "Perl interface to Janrain's RPX service"
author:
  - 'Scott McWhirter <konobi@cpan.org>'
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  Data::Dump: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.28'
  Test::Exception: '0'
  Test::More: '0.88'
  mocked: '0'
  perl: '5.006'
  unmocked: '0'
configure_requires:
  Module::Build: '0.28'
dynamic_config: '0'
generated_by: 'Dist::Zilla version 5.034, CPAN::Meta::Converter version 2.150001'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-API-RPX
provides:
  Net::API::RPX:
    file: lib/Net/API/RPX.pm
    version: '0.05'
  Net::API::RPX::Exception:
    file: lib/Net/API/RPX/Exception.pm
    version: '0.05'
  Net::API::RPX::Exception::Network:
    file: lib/Net/API/RPX/Exception/Network.pm
    version: '0.05'
  Net::API::RPX::Exception::Service:
    file: lib/Net/API/RPX/Exception/Service.pm
    version: '0.05'
  Net::API::RPX::Exception::Usage:
    file: lib/Net/API/RPX/Exception/Usage.pm
    version: '0.05'
requires:
  JSON::Any: '0'
  LWP::UserAgent: '0'
  Moose: '0'
  Throwable::Error: '0'
  Throwable::X: '0'
  URI: '0'
  namespace::autoclean: '0'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/kentnl/Net-API-RPX
  repository: https://github.com/kentnl/Net-API-RPX.git
version: '0.05'
x_BuiltWith:
  modules:
    Data::Dump: '1.22'
    File::Spec: '3.53'
    IO::Handle: '1.35'
    IPC::Open3: '1.18'
    JSON::Any: '1.38'
    LWP::UserAgent: '6.13'
    Module::Build: '0.4211'
    Moose: '2.1403'
    Pod::Coverage::TrustPod: '0.100003'
    Test::CPAN::Changes: '0.30'
    Test::CPAN::Meta: '0.24'
    Test::EOL: '1.5'
    Test::Exception: '0.38'
    Test::Kwalitee: '1.22'
    Test::More: 1.301001_098
    Test::Pod: '1.48'
    Test::Pod::Coverage: '1.10'
    Throwable::Error: '0.200012'
    Throwable::X: '0.007'
    URI: '1.67'
    mocked: '0.09'
    namespace::autoclean: '0.24'
    strict: '1.09'
    unmocked: '0.01'
    version: '0.9912'
    warnings: '1.31'
  perl:
    original: v5.21.9
    qv: 1
    version:
      - 5
      - 21
      - 9
  perl-config:
    gccversion: 4.9.2
    git_commit_date: '2015-02-10 17:02:59 +1100'
    git_commit_id: 5904c5c0c031fad19e61f5d279d624a91a196e02
    git_describe: v5.21.8-270-g5904c5c
    myarchname: x86_64-linux
    osname: linux
  platform: linux
  uname: 'Linux 3.19.0-gentoo x86_64 GenuineIntel GNU/Linux'
x_Dist_Zilla:
  perl:
    version: '5.021009'
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      config:
        Dist::Zilla::Plugin::Git::NextVersion:
          first_version: '0.03'
          version_by_branch: '0'
          version_regexp: (?^u:^(.*)-source$)
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: Git::NextVersion
      version: '2.030'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: GithubMeta
      version: '0.46'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: MetaProvides::Package/AUTOVIV/:InstallModulesPM
              version: '5.034'
        Dist::Zilla::Role::MetaProvider::Provider:
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
      name: MetaProvides::Package
      version: '2.003001'
    -
      class: Dist::Zilla::Plugin::MetaData::BuiltWith
      config:
        Dist::Zilla::Plugin::MetaData::BuiltWith:
          _stash_key: x_BuiltWith
          external_file_name: misc/built_with.json
          show_config: '1'
          show_uname: '1'
          uname:
            uname_args:
              - -s
              - -o
              - -r
              - -m
              - -i
            uname_call: uname
          use_external_file: ~
      name: MetaData::BuiltWith
      version: '1.004002'
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      config:
        Dist::Zilla::Plugin::GatherDir:
          exclude_filename: []
          exclude_match: []
          follow_symlinks: '0'
          include_dotfiles: '1'
          prefix: ''
          prune_directory: []
          root: .
        Dist::Zilla::Plugin::Git::GatherDir:
          include_untracked: '0'
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: Git::GatherDir
      version: '2.030'
    -
      class: Dist::Zilla::Plugin::License
      name: License
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: MetaYAML
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: Manifest
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: MetaTests
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: PodCoverageTests
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: PodSyntaxTests
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: ReportVersions::Tiny
      version: '1.10'
    -
      class: Dist::Zilla::Plugin::Test::Kwalitee
      config:
        Dist::Zilla::Plugin::Test::Kwalitee:
          filename: xt/release/kwalitee.t
          skiptest: []
      name: Test::Kwalitee
      version: '2.11'
    -
      class: Dist::Zilla::Plugin::EOLTests
      config:
        Dist::Zilla::Plugin::Test::EOL:
          filename: xt/release/eol.t
          finder:
            - ':InstallModules'
            - ':ExecFiles'
            - ':TestFiles'
          trailing_whitespace: '1'
      name: EOLTests
      version: '0.17'
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: Test::MinimumVersion
      version: '2.000006'
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          bail_out_on_fail: '0'
          fail_on_warning: author
          fake_home: '0'
          filename: t/00-compile.t
          module_finder:
            - ':InstallModules'
          needs_display: '0'
          phase: test
          script_finder:
            - ':ExecFiles'
          skips: []
      name: Test::Compile
      version: '2.051'
    -
      class: Dist::Zilla::Plugin::Test::Perl::Critic
      name: Test::Perl::Critic
      version: '3.000'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: PruneCruft
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: ManifestSkip
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: PkgVersion
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.011'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.011'
            -
              class: Pod::Weaver::Plugin::SingleEncoding
              name: '@Default/SingleEncoding'
              version: '4.011'
            -
              class: Pod::Weaver::Section::Name
              name: '@Default/Name'
              version: '4.011'
            -
              class: Pod::Weaver::Section::Version
              name: '@Default/Version'
              version: '4.011'
            -
              class: Pod::Weaver::Section::Region
              name: '@Default/prelude'
              version: '4.011'
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: '4.011'
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: '4.011'
            -
              class: Pod::Weaver::Section::Generic
              name: OVERVIEW
              version: '4.011'
            -
              class: Pod::Weaver::Section::Collect
              name: ATTRIBUTES
              version: '4.011'
            -
              class: Pod::Weaver::Section::Collect
              name: METHODS
              version: '4.011'
            -
              class: Pod::Weaver::Section::Collect
              name: FUNCTIONS
              version: '4.011'
            -
              class: Pod::Weaver::Section::Leftovers
              name: '@Default/Leftovers'
              version: '4.011'
            -
              class: Pod::Weaver::Section::Region
              name: '@Default/postlude'
              version: '4.011'
            -
              class: Pod::Weaver::Section::Authors
              name: '@Default/Authors'
              version: '4.011'
            -
              class: Pod::Weaver::Section::Legal
              name: '@Default/Legal'
              version: '4.011'
      name: PodWeaver
      version: '4.006'
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: NextRelease
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::Authority
      name: Authority
      version: '1.009'
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: '1'
      name: ModuleBuild
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: ReadmeFromPod
      version: '0.30'
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: Test::CPAN::Changes
      version: '0.009'
    -
      class: Dist::Zilla::Plugin::CheckExtraTests
      name: CheckExtraTests
      version: '0.025'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: TestRelease
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: ConfirmRelease
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - dist.ini
            - Changes
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: Git::Check
      version: '2.030'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          signed: '0'
          tag: 0.05-source
          tag_format: '%v-source'
          tag_message: v%v
          time_zone: local
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: tag_master
      version: '2.030'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%v%n%n%c
          time_zone: local
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - dist.ini
            - Changes
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: Git::Commit
      version: '2.030'
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      config:
        Dist::Zilla::Plugin::Git::CommitBuild:
          branch: build/%b
          build_root: ~
          message: 'Build results of %h (on %b)'
          multiple_inheritance: '0'
          release_branch: releases
          release_message: 'Build results of %h (on %b)'
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: Git::CommitBuild
      version: '2.030'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: releases
          signed: '0'
          tag: '0.05'
          tag_format: '%v'
          tag_message: v%v
          time_zone: local
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: tag_release
      version: '2.030'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: UploadToCPAN
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::Twitter
      name: Twitter
      version: '0.026'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '5.034'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: MetaProvides::Package/AUTOVIV/:InstallModulesPM
      version: '5.034'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '5.034'
x_authority: cpan:KONOBI
